# Generated by Django 5.1.1 on 2025-03-18 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comix', '0007_alter_orderitem_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
